// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbTWqFtodNcs-6mj_HN0YjWUkZGFd3l7s',
    appId: '1:417544252287:web:c296f0cc547cc41e3a484a',
    messagingSenderId: '417544252287',
    projectId: 'shopywell-dc636',
    authDomain: 'shopywell-dc636.firebaseapp.com',
    storageBucket: 'shopywell-dc636.firebasestorage.app',
    measurementId: 'G-W15QE04SK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6-R4pvzrkt4vUQvKFSt4atQn7LrhUlxY',
    appId: '1:417544252287:android:2ebf3dc7ae50d8993a484a',
    messagingSenderId: '417544252287',
    projectId: 'shopywell-dc636',
    storageBucket: 'shopywell-dc636.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALbaiyV8lcJKdI9PQo-47_9OKWsW8kzQ4',
    appId: '1:417544252287:ios:4595424ad8c72eab3a484a',
    messagingSenderId: '417544252287',
    projectId: 'shopywell-dc636',
    storageBucket: 'shopywell-dc636.firebasestorage.app',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALbaiyV8lcJKdI9PQo-47_9OKWsW8kzQ4',
    appId: '1:417544252287:ios:4595424ad8c72eab3a484a',
    messagingSenderId: '417544252287',
    projectId: 'shopywell-dc636',
    storageBucket: 'shopywell-dc636.firebasestorage.app',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbTWqFtodNcs-6mj_HN0YjWUkZGFd3l7s',
    appId: '1:417544252287:web:91e59e6b87dc3ec93a484a',
    messagingSenderId: '417544252287',
    projectId: 'shopywell-dc636',
    authDomain: 'shopywell-dc636.firebaseapp.com',
    storageBucket: 'shopywell-dc636.firebasestorage.app',
    measurementId: 'G-6JRC33CRL4',
  );

}